apiVersion: v1
kind: ConfigMap
metadata:
  name: educorenextgen-website-config
  namespace: educorenextgen
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_TELEMETRY_DISABLED: "1"
