apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: educorenextgen-certificate
  namespace: educorenextgen
spec:
  secretName: wildcard-educorenextgen-tls
  issuerRef:
    name: skyfobscloud-prod
    kind: ClusterIssuer

  dnsNames:
    - educorenextgen.com
    - "*.educorenextgen.com"